version: "3.7"

services:
  jupyter-pyspark:
    build: .
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./:/home/jovyan/work
      - jupyter-data:/home/jovyan/.jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"

volumes:
  jupyter-data:
